version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Omolade3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service:
    build: ./auth-service
    container_name: auth_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: sulaimonlawal
      SPRING_DATASOURCE_PASSWORD: Omolade3

      # ✅ SuperAdmin seeding environment variables (read in Spring Boot)
      SEED_SUPERADMIN: "true"
      SUPERADMIN_EMAIL: superadmin@yourdomain.com
      SUPERADMIN_PASSWORD: YourStrongPassword123
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    restart: always

volumes:
  postgres_data:
